### ISSUE TITLE
How to add "Service Monitor"?

### ISSUE THREAD

**Issue by keivanipchihagh** [vesoft-inc/nebula-stats-exporter#63]
I want to add Service Monitor to the helm chart to make it accessible to Prometheus, but don't see how I can make it work.

**Comment by kqzh** [comment]
hi @keivanipchihagh , you can refer to this yaml to add a serviceMonitor
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
  name: np-prometheus-nebula-stats-exporter
  namespace: prometheus-system
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: 15s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
```
